version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.01  # dockerの実行環境を含むイメージ(docker, docker-compose)
    steps:
      - setup_remote_docker # circleciのDockerデーモンを起動（Docker実行環境に必須）
      - checkout
      - run: docker-compose up --build -d
      - run: docker-compose ps -a 
      - run: ls
      - run: rails db:create
      # - run: docker-compose exec web rails db:migrate
      # - run: docker-compose exec web rails test 
      # - run: docker-compose exec web pwd
      # - run: docker-compose exec web rails s -b 0.0.0.0

workflows:
  build-test:
    jobs:
      - build

