version: 2.1
jobs:
  build:
    machine:
      # Docker実行環境をUbuntuのVMとして作成する
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - run: docker-compose up --build -d
      - run: docker-compose exec --env 'RAILS_ENV=test' web rails db:create
      - run: docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
      - run: docker-compose exec --env 'RAILS_ENV=test' web rails test

workflows:
  build-test:
    jobs:
      - build

