version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.01  # dockerの実行環境を含むイメージ(docker, docker-compose)
    steps:
      - checkout
      - setup_remote_docker # circleciのDockerデーモンを起動（Docker実行環境に必須）
      - run: docker-compose up --build -d
      - run: docker-compose exec --env 'RAILS_ENV=test' web rails db:create
      - run: docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
      - run: docker-compose exec --env 'RAILS_ENV=test' web rails test

workflows:
  build-test:
    jobs:
      - build

