version: 2.1
jobs:
  build:
    machine:
      # Docker実行環境をUbuntuのVMとして作成する
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - run: docker-compose up --build -d
      - run: docker-compose ps -a 
      - run: docker-compose exec web rails db:create --env 'RAILS_ENV=test'
      - run: docker-compose exec web rails db:migrate --env 'RAILS_ENV=test'
      - run: docker-compose exec web rails test --env 'RAILS_ENV=test'

workflows:
  build-test:
    jobs:
      - build

